server:
  port: 8888
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

#db配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234


mybatis:
  type-aliases-package: com.boss.rbac_learning.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
